name: Manual Deployment from Artifactory to Windows Servers

on:
  workflow_dispatch:
    inputs:
      server:
        description: 'Target Server (test1, test2, test3)'
        required: true
        type: choice
        options:
          - test1
          - test2
          - test3

jobs:
  deploy:
    runs-on: [self-hosted, Windows]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download zip from Artifactory
      shell: pwsh
      run: |
        $artifactoryUrl = "https://artifactory.example.com/eapps/file/eapps.exe.zip"
        $pathToSave = "eapps.exe.zip"
        Invoke-RestMethod -Uri $artifactoryUrl -OutFile $pathToSave -Credential (New-Object System.Management.Automation.PSCredential ('${{ secrets.ARTIFACTORY_USER }}', (ConvertTo-SecureString '${{ secrets.ARTIFACTORY_PASSWORD }}' -AsPlainText -Force)))

    - name: Deploy to Selected Windows Server
      shell: pwsh
      run: |
        $serverName = ${{ github.event.inputs.server }}
        $destinationPath = "D:\\Data\\testclientapp\\GreaterChina\\HongKong\\HKVantest\\"
        $username = "${{ secrets.WINDOWS_USER_$serverName }}"
        $password = ConvertTo-SecureString "${{ secrets.WINDOWS_PASSWORD_$serverName }}" -AsPlainText -Force
        $Cred = New-Object System.Management.Automation.PSCredential -ArgumentList ($username, $password)
        $Session = New-PSSession -ComputerName $serverName -Credential $Cred
        Copy-Item ".\eapps.exe.zip" -Destination $destinationPath -ToSession $Session
        Get-PSSession | Remove-PSSession
