name: Deploy Files to Windows VM

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the action on

jobs:
  deploy:
    runs-on: LAPTOP-3CT3U1FA  # Use a Windows runner

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set Execution Policy
      run: |
        # Set execution policy to allow script execution
        Set-ExecutionPolicy Bypass -Scope Process -Force

    - name: Copy files to VM path
      run: |
        # Copy all the files in the repo to the specified path on the VM
        Copy-Item -Path ${{ github.workspace }}\* -Destination "D:\copy-file" -Recurse
      shell: powershell

