name: Copy PY Files with DDMMYY Timeline on Windows VM

on:
  push:
    branches:
      - main  # Trigger the action on the 'main' branch

jobs:
  deploy:
    runs-on: LAPTOP-3CT3U1FA  # Use your specific runner

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Copy .py files with DDMMYY timeline to VM path
      run: |
        $dateSuffix = (Get-Date).ToString("ddMMyy")
        Get-ChildItem -Path ${{ github.workspace }}\*.txt -Recurse | ForEach-Object {
            $newName = "$($_.BaseName)_$dateSuffix$($_.Extension)"
            Copy-Item -Path $_.FullName -Destination "D:\copy-file\$newName"
        }
      shell: powershell
