name: Deploy Files to Windows VM

on: 
  push:
    paths:
      - '**' # This will trigger the action for any push event for any file/folder

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set Execution Policy and Copy Files
      run: |
        # Set execution policy to allow script execution for this session
        Set-ExecutionPolicy Bypass -Scope Process -Force
        # Copy all the files from the repo to the specified path on the VM
        Copy-Item -Path "${{ github.workspace }}\*" -Destination "C:\copy-file" -Recurse
      shell: powershell
