name: Copy PY Files with DDMMYY Timeline on Windows VM

on:
  push:
    branches:
      - main  # Trigger the action on the 'main' branch

jobs:
  deploy:
    runs-on: LAPTOP-3CT3U1FA  # Use your specific runner

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Overwrite py files to VM path
      run: |
        Copy-Item -Path ${{ github.workspace }}\*.py -Destination "D:\copy-file" -Recurse
      shell: powershell
