name: Copy files to Windows VM

on:
  push:
    paths:
      - '**'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set Execution Policy and Copy files
      run: |
        # Copy files to the desired path on the Windows VM
        powershell -ExecutionPolicy Bypass -Command {
          Copy-Item -Path $env:GITHUB_WORKSPACE\* -Destination 'C:\copy-file' -Recurse -Force
        }
      shell: powershell


